apiVersion: v1
kind: Service
metadata:
  name: {{ include "lineq.fullname" . }}-http
  labels:
    {{- include "lineq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.httpService.type }}
  ports:
    - port: {{ .Values.httpService.port }}
      targetPort: {{ .Values.httpService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "lineq.selectorLabels" . | nindent 4 }}
