apiVersion: v1
kind: Service
metadata:
  name: {{ include "lineq.fullname" . }}-tcp
  labels:
    {{- include "lineq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tcpService.type }}
  ports:
    - port: {{ .Values.tcpService.port }}
      targetPort: {{ .Values.tcpService.port }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "lineq.selectorLabels" . | nindent 4 }}
